services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: api
    volumes:
      - './packages/api/src:/app/packages/api/src'
      - './pinguin.dev.yaml:/etc/pinguin/pinguin.yaml'
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dashboard
    volumes:
      - './packages/dashboard/src:/app/packages/dashboard/src'
      - './packages/dashboard/index.html:/app/packages/dashboard/index.html'
  proxy:
    image: nginx:stable-alpine
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:8080'
  agent-1:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: agent
    volumes:
      - './packages/api/dist/main.d.ts:/app/packages/api/dist/main.d.ts'
      - './packages/agent/src:/app/packages/agent/src'
    environment:
      - NODE_ID=agent-1
      - API_SERVER=http://api:3000
  agent-2:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: agent
    volumes:
      - './packages/api/dist/main.d.ts:/app/packages/api/dist/main.d.ts'
      - './packages/agent/src:/app/packages/agent/src'
    environment:
      - NODE_ID=agent-2
      - API_SERVER=http://api:3000
