# syntax=docker/dockerfile:1

# target: api

FROM node:22-bookworm AS api

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/api/package.json ./packages/api/

RUN npm -w @pinguin/api ci

COPY packages/api/rollup.config.mjs packages/api/tsconfig.json ./packages/api/

EXPOSE 3000

CMD [ "npm", "-w", "@pinguin/api", "run", "dev" ]
