# syntax=docker/dockerfile:1

# target: common

FROM node:22-bookworm AS common

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/api/package.json ./packages/api/
COPY packages/agent/package.json ./packages/agent/
COPY packages/dashboard/package.json ./packages/dashboard/

RUN npm ci

# target: api

FROM common AS api

COPY packages/api/rollup.config.mjs packages/api/tsconfig.json ./packages/api/

EXPOSE 3000

CMD [ "npm", "-w", "@pinguin/api", "run", "dev" ]

# target: agent

FROM common AS agent

RUN <<EOF
set -eux
apt-get update
apt-get install --no-install-recommends -y \
        iputils-ping
rm -rf /var/lib/apt/lists/*
EOF

COPY packages/agent/rollup.config.mjs packages/agent/tsconfig.json ./packages/agent/

EXPOSE 3000

CMD [ "npm", "-w", "@pinguin/agent", "run", "dev" ]

# target: dashboard

FROM common AS dashboard

COPY packages/dashboard/tsconfig.json packages/dashboard/vite.config.ts ./packages/dashboard/

EXPOSE 8080

CMD [ "npm", "-w", "@pinguin/dashboard", "run", "dev" ]
